[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheckProbes]]
type = "HTTP"
path = "/"

[deploy.releaseCommand]
template = "python manage.py migrate"